version: '2'

services:
  best_python_docker:
    image: best_python_docker
    container_name: best_python_docker
    hostname: bpd
    restart: unless-stopped
    #environment:
      #- PORT=1235
    ports:
      - "1234:8000"
      #- "1235:1235"
