version: '3'

services:
  best_python_docker:
    image: best_python_docker
    container_name: best_python_docker
    hostname: bpd
    restart: unless-stopped
    #environment:
      #- PORT=1235
    ports:
      - "1234:8000"
      #- "1235:1235"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    # Uncomment if need temporary files
    #tmpfs:
    #  - /tmp

    # Limit the container
    # always has quarter of a CPU available but no more than half
    # will have 20Mb memory but constrained to 200Mb
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 20M
